# **Tensor Operations (Pytorch)**

## **Creating a 2 dimensional vector**

In [1]:
import torch
import numpy
torch.tensor([[0.1, 0.2],[0.3, 0.4]])

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

## **Shape of a tensor**

In [2]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]])
a.shape

torch.Size([2, 2])

In [3]:
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

## **Shape of a tensor (continued)**

In [4]:
b = torch.tensor([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6]])

b

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [0.5000, 0.6000]])

In [5]:
b.shape

torch.Size([3, 2])

## **Creating tensors with arbitary dimensions**

In [6]:
c = torch.tensor([[[0.1],[0.2]],[[0.3],[0.4]]])

c.shape

torch.Size([2, 2, 1])

In [7]:
c

tensor([[[0.1000],
         [0.2000]],

        [[0.3000],
         [0.4000]]])

## **Tensors with Numpy**

In [8]:
a = torch.tensor(numpy.array([[0.1, 0.2],[0.3, 0.4]]))

a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], dtype=torch.float64)

In [9]:
a.shape

torch.Size([2, 2])

## **Tensors from Numpy**

In [10]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
tensor_a = torch.from_numpy(a)
tensor_a

tensor([1, 2, 3, 4, 5])

## **Defining tensor datatypes**

In [11]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float32)
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

In [12]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float64)    
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], dtype=torch.float64)

In [13]:
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float16)     
a

tensor([[0.1000, 0.2000],
        [0.3000, 0.3999]], dtype=torch.float16)

## **Constructing tensors with random values**

In [14]:
r = torch.rand(2,2,2)
r

tensor([[[0.7020, 0.0946],
         [0.9031, 0.4632]],

        [[0.7060, 0.4203],
         [0.8546, 0.9928]]])

In [15]:
r.shape

torch.Size([2, 2, 2])

## **Tensors with zeros**

In [16]:
zeros = torch.zeros(2,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [17]:
zeros.shape

torch.Size([2, 2, 3])

## **Tensors of ones**

In [18]:
ones = torch.ones(2,2,3)

ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [19]:
ones.shape

torch.Size([2, 2, 3])

## **Identity maxtix tensors**

In [20]:
i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
i.shape

torch.Size([3, 3])

## **Tensors filled with an arbitary value**

In [22]:
f = torch.full((3,3), 0.42)
f

tensor([[0.4200, 0.4200, 0.4200],
        [0.4200, 0.4200, 0.4200],
        [0.4200, 0.4200, 0.4200]])

In [23]:
f.shape

torch.Size([3, 3])

## **Tensors with linearly spaced floating-point numbers**

In [24]:
lin = torch.linspace(0, 20, steps=5)
lin

tensor([ 0.,  5., 10., 15., 20.])

## **Tensors with logarithmically spaced floating-point numbers**

In [25]:
log = torch.logspace(-3, 3, steps=4)
log

tensor([1.0000e-03, 1.0000e-01, 1.0000e+01, 1.0000e+03])

## **Creating a tensor with dimensions similar to another tensor**

In [26]:
a = torch.tensor([[0.5, 0.5],[0.5, 0.5]])
b = torch.zeros_like(a)
b

tensor([[0., 0.],
        [0., 0.]])

In [27]:
c = torch.ones_like(a)
c

tensor([[1., 1.],
        [1., 1.]])

## **Tensor with int dtype**

In [28]:
i = torch.tensor([[1,2],[3,4]])
i

tensor([[1, 2],
        [3, 4]])

In [29]:
i.dtype

torch.int64

In [30]:
i = torch.tensor([[1,2],[3,4]], dtype=torch.int)
i

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

## **Tensors as a range of integers**

In [31]:
a = torch.arange(1,10, step=2)
a

tensor([1, 3, 5, 7, 9])

## **Tensors with random permutation of integers**

In [32]:
r = torch.randperm(10)
r

tensor([3, 5, 2, 1, 0, 4, 8, 6, 9, 7])

# **Tensor Munging Operations**

## **Accessing individual members of a tensor**

In [33]:
a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [34]:
print(a[0][0])
print(a[0][1])       
print(a[1][0]) 
print(a[1][1])
print(a.shape)

tensor(1)
tensor(2)
tensor(3)
tensor(4)
torch.Size([2, 2])


## **Accessing values from a tensor with a single value**

In [35]:
a = torch.tensor([[[0.42]]])
print(a)
print(a.shape)
print(a.item())

tensor([[[0.4200]]])
torch.Size([1, 1, 1])
0.41999998688697815


## **Reshaping a tensor**

In [36]:
a = torch.zeros(10)
print(a)
print(a.shape)
b = a.view(2,5)
print(b)
print(b.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


## **Verifying the size of a tensor after reshaping**

In [37]:
a = torch.arange(1,10)
print(a)
print(a.shape)
b = a.view(3,3)
print(b)
print(b.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


## **Concatenating two tensors**

In [38]:
a = torch.zeros(2,2)
print(a)
print(a.shape)
b = torch.cat([a,a,a],0)
print(b)
print(b.shape)
c = torch.cat([a,a,a],1)
print(c)
print(c.shape)

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
torch.Size([6, 2])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
torch.Size([2, 6])


## **Stacking tensors together**

In [39]:
a = torch.zeros(2,1)
print(a)
print(a.shape)
b = torch.stack([a,a,a], 0)
print(b)
print(b.shape)
c = torch.stack([a,a,a], 1)
print(c)
print(c.shape)
d = torch.stack([a,a,a], 2)
print(d)
print(d.shape)

tensor([[0.],
        [0.]])
torch.Size([2, 1])
tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])
torch.Size([3, 2, 1])
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])
torch.Size([2, 3, 1])
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])
torch.Size([2, 1, 3])


## **Chunking/chopping tensors** 

In [40]:
a = torch.zeros(10, 1)
print(a)
print(a.shape)
b = torch.chunk(a, 5, 0)
print(b)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
torch.Size([10, 1])
(tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]))


## **Chunking/chopping tensors continued**

In [41]:
d = torch.chunk(a, 3, 0)
print(d)

(tensor([[0.],
        [0.],
        [0.],
        [0.]]), tensor([[0.],
        [0.],
        [0.],
        [0.]]), tensor([[0.],
        [0.]]))


## **Splitting tensors**

In [42]:
a = torch.zeros(10,1)
print(a)
print(a.shape)
b = torch.split(a,2,0)
print(b)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
torch.Size([10, 1])
(tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]), tensor([[0.],
        [0.]]))


## **Extracting parts of tensors using index_select**

In [43]:
a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])
print(a)
print(a.shape)
index = torch.LongTensor([0, 1])
b = torch.index_select(a, 0, index)
                
print(b)
print(b.shape)
c = torch.index_select(a, 1, index)
                        
print(c)
print(c.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])
torch.Size([3, 2])


## **Selecting elements from a tensor using masked_select**

In [44]:
a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])

print(a)
print(a.shape)
                
mask = torch.ByteTensor([[0, 1, 0],[1, 1, 1],[0, 1, 0]])
                
print(mask)
print(mask.shape)                             
b = torch.masked_select(a, mask)
                                
print(b)                      
print(b.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])
tensor([[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]], dtype=torch.uint8)
torch.Size([3, 3])
tensor([2., 4., 5., 6., 8.])
torch.Size([5])


/tmp/ipykernel_264/1963178790.py:10: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1356.)
  b = torch.masked_select(a, mask)


## **Reshaping tensor with squeeze**

In [45]:
a = torch.zeros(2,2,1)
print(a)
print(a.shape)
                          
b = a.squeeze()                        
print(b)
print(b.shape)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
torch.Size([2, 2, 1])
tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])


## **Reshaping tensor with unsqueeze**

In [46]:
a = torch.zeros(2,2)
print(a)
print(a.shape)
        
b = torch.unsqueeze(a, 0)
print(b)
print(b.shape)
                 
c = torch.unsqueeze(a, 1)
print(c)
print(c.shape)
                         
d = torch.unsqueeze(a, 2)
print(d)
print(d.shape)

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])
tensor([[[0., 0.],
         [0., 0.]]])
torch.Size([1, 2, 2])
tensor([[[0., 0.]],

        [[0., 0.]]])
torch.Size([2, 1, 2])
tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
torch.Size([2, 2, 1])


## **Extracting parts of a tensor using unbind**

In [47]:
a
print(a.shape)                
print(torch.unbind(a, 0))           
print(torch.unbind(a, 1))

torch.Size([2, 2])
(tensor([0., 0.]), tensor([0., 0.]))
(tensor([0., 0.]), tensor([0., 0.]))


## **Constructing tensor from existing tensor using where clause**

In [48]:
a = torch.zeros(3,3)
print(a)
print(a.shape)
                
b = torch.ones(3,3)
print(b)
print(b.shape)
                                
c = torch.rand(3,3)
print(c)
print(c.shape)
                                                
d = torch.where(c > 0.5, a, b)
print(d)
print(d.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])
tensor([[0.2575, 0.0373, 0.0216],
        [0.0179, 0.3146, 0.6050],
        [0.4288, 0.1605, 0.8523]])
torch.Size([3, 3])
tensor([[1., 1., 1.],
        [1., 1., 0.],
        [1., 1., 0.]])
torch.Size([3, 3])


## **Logical operations on tensors using any and all**

In [49]:
a = torch.rand(3,3)
print(a)
print(a.shape)

print(torch.any(a > 0))              
print(torch.any(a > 1.0))          
print(torch.all(a > 0))      
print(torch.all(a > 1.0))

tensor([[0.4944, 0.3594, 0.5036],
        [0.9726, 0.6347, 0.3419],
        [0.2110, 0.7173, 0.9738]])
torch.Size([3, 3])
tensor(True)
tensor(False)
tensor(True)
tensor(False)


## **Reshaping tensors**

In [50]:
a = torch.arange(1,10)
print(a)

b = a.view(3,3)
print(b)
print(b.shape)
                
c = a.view(3,-1)
print(c)
print(c.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


## **Collapsing the dimensions of a tensor using flatten**

In [51]:
a = torch.ones([2,2,2,2])
print(a)
print(a.shape)


b = torch.flatten(a)
print(b)
print(b.shape)

c = torch.flatten(a, start_dim=0)
print(c)
print(c.shape)


d = torch.flatten(a, start_dim=1)
print(d)
print(d.shape)

e = torch.flatten(a, start_dim=2)
print(e)
print(e.shape)

f = torch.flatten(a, start_dim=3)
print(f)
print(f.shape)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
torch.Size([2, 2, 2, 2])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([16])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([16])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([2, 8])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 2, 4])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
torch.Size([2, 2, 2, 2])


## **Extract values from tensor using gather**

In [52]:
a = torch.rand(4,4)
print(a)
print(a.shape)
                        
b = torch.LongTensor([[0,1,2,3]])
print(b)
print(b.shape)

c = a.gather(0,b)
print(c)
print(c.shape)
                        
d = torch.LongTensor([[0],[1],[2],[3]])
print(d)
print(d.shape)

e = a.gather(1,d)
print(e)
print(e.shape)

tensor([[0.2135, 0.4237, 0.5009, 0.4197],
        [0.9047, 0.1540, 0.2839, 0.5638],
        [0.0757, 0.8640, 0.7830, 0.3918],
        [0.0481, 0.0696, 0.1963, 0.4586]])
torch.Size([4, 4])
tensor([[0, 1, 2, 3]])
torch.Size([1, 4])
tensor([[0.2135, 0.1540, 0.7830, 0.4586]])
torch.Size([1, 4])
tensor([[0],
        [1],
        [2],
        [3]])
torch.Size([4, 1])
tensor([[0.2135],
        [0.1540],
        [0.7830],
        [0.4586]])
torch.Size([4, 1])


## **Augmenting tensors values with scatter**

In [53]:
a = torch.rand(4,4)
print(a)
print(a.shape)

                        
index = torch.LongTensor([[0,1,2,3]])
print(index)
print(index.shape)
                        
values = torch.zeros(1,4)
print(values)
print(values.shape)
                        
result = a.scatter(0, index, values)
print(result)
print(result.shape)
print(a)

tensor([[0.4459, 0.0515, 0.9351, 0.7622],
        [0.6363, 0.8391, 0.3344, 0.9707],
        [0.3943, 0.5922, 0.2198, 0.9519],
        [0.2102, 0.0719, 0.9947, 0.9867]])
torch.Size([4, 4])
tensor([[0, 1, 2, 3]])
torch.Size([1, 4])
tensor([[0., 0., 0., 0.]])
torch.Size([1, 4])
tensor([[0.0000, 0.0515, 0.9351, 0.7622],
        [0.6363, 0.0000, 0.3344, 0.9707],
        [0.3943, 0.5922, 0.0000, 0.9519],
        [0.2102, 0.0719, 0.9947, 0.0000]])
torch.Size([4, 4])
tensor([[0.4459, 0.0515, 0.9351, 0.7622],
        [0.6363, 0.8391, 0.3344, 0.9707],
        [0.3943, 0.5922, 0.2198, 0.9519],
        [0.2102, 0.0719, 0.9947, 0.9867]])


# **Mathematical Operations**

## **Validating if given tensors are within a tolerance level**

In [54]:
a = torch.rand(3,3)
print(a)
b = a + a * 1e-3
                
print(b)
print(torch.allclose(a,b,rtol=1e-1))
print(torch.allclose(a,b,rtol=1e-2))
print(torch.allclose(a,b,rtol=1e-3))
print(torch.allclose(a,b,rtol=1e-4))
print(torch.allclose(a,b,atol=1e-1))
print(torch.allclose(a,b,atol=1e-2))
print(torch.allclose(a,b,atol=1e-3))
print(torch.allclose(a,b,atol=1e-4))

tensor([[0.5316, 0.4201, 0.3297],
        [0.3093, 0.9484, 0.3638],
        [0.0935, 0.8684, 0.9244]])
tensor([[0.5321, 0.4205, 0.3301],
        [0.3096, 0.9494, 0.3641],
        [0.0936, 0.8692, 0.9253]])
True
True
True
False
True
True
True
False


## **Extracting dimensions of minimum and maximum values in a given tensor**

In [55]:
a = torch.rand(3,3)
print(a)
print(a.shape)
                
print(torch.argmax(a, dim=0))
print(torch.argmax(a, dim=1))
print(torch.argmin(a, dim=0))
print(torch.argmin(a, dim=1))

tensor([[0.4170, 0.8331, 0.9014],
        [0.2764, 0.2613, 0.1822],
        [0.1347, 0.8666, 0.8337]])
torch.Size([3, 3])
tensor([0, 2, 0])
tensor([2, 0, 1])
tensor([2, 1, 1])
tensor([0, 2, 0])


## **Extracting the indices of sorted values of a tensor**

In [56]:
a = torch.rand(3,3)
print(a)
print(a.shape)

print(torch.argsort(a, dim=0))
print(torch.argsort(a, dim=1))

tensor([[0.8268, 0.0900, 0.1535],
        [0.8230, 0.3314, 0.8989],
        [0.3340, 0.3729, 0.2535]])
torch.Size([3, 3])
tensor([[2, 0, 0],
        [1, 1, 2],
        [0, 2, 1]])
tensor([[1, 2, 0],
        [1, 0, 2],
        [2, 0, 1]])


## **Cumulative sum along a dimension of the tensor**

In [57]:
a = torch.rand(3,3)
print(a)
print(a.shape)
                
b = torch.cumsum(a, dim=0)
print(b)
print(b.shape)

c = torch.cumsum(a, dim=1)
print(c)
print(c.shape)

tensor([[0.3704, 0.3661, 0.7640],
        [0.5153, 0.4394, 0.8255],
        [0.6062, 0.2864, 0.6346]])
torch.Size([3, 3])
tensor([[0.3704, 0.3661, 0.7640],
        [0.8857, 0.8055, 1.5895],
        [1.4919, 1.0919, 2.2241]])
torch.Size([3, 3])
tensor([[0.3704, 0.7366, 1.5005],
        [0.5153, 0.9546, 1.7801],
        [0.6062, 0.8926, 1.5272]])
torch.Size([3, 3])


## **Cumulative product along a dimension of the tensor**

In [58]:
a = torch.rand(3,3)
print(a)
print(a.shape)
                
b = torch.cumprod(a, dim=0)
print(b)
print(b.shape)
                                
c = torch.cumprod(a, dim=1)
print(c)
print(c.shape)

tensor([[0.0901, 0.7662, 0.9067],
        [0.5943, 0.2930, 0.0918],
        [0.3406, 0.0487, 0.9898]])
torch.Size([3, 3])
tensor([[0.0901, 0.7662, 0.9067],
        [0.0535, 0.2245, 0.0833],
        [0.0182, 0.0109, 0.0824]])
torch.Size([3, 3])
tensor([[0.0901, 0.0690, 0.0626],
        [0.5943, 0.1741, 0.0160],
        [0.3406, 0.0166, 0.0164]])
torch.Size([3, 3])


## **Absolute value of a tensor**

In [59]:
a = torch.tensor([[1,-1,1],[1,-1,1],[1,-1,1]])
print(a)

b = torch.abs(a)
print(b)

tensor([[ 1, -1,  1],
        [ 1, -1,  1],
        [ 1, -1,  1]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


## **Clamping values within a tensor**

In [60]:
a = torch.rand(3,3)
print(a)

b = torch.clamp(a, min=0.25, max=0.50)
print(b)

tensor([[0.4468, 0.1840, 0.1446],
        [0.4010, 0.4465, 0.7896],
        [0.0149, 0.0366, 0.8741]])
tensor([[0.4468, 0.2500, 0.2500],
        [0.4010, 0.4465, 0.5000],
        [0.2500, 0.2500, 0.5000]])


## **Ceil and floor operations within a tensor**

In [61]:
a = torch.rand(3,3) * 100
print(a)

b = torch.floor(a)
print(b)

c = torch.ceil(a)
print(c)

tensor([[99.5164, 70.1482,  8.3628],
        [19.9827, 39.4838, 96.7118],
        [12.5187, 29.8814, 85.1419]])
tensor([[99., 70.,  8.],
        [19., 39., 96.],
        [12., 29., 85.]])
tensor([[100.,  71.,   9.],
        [ 20.,  40.,  97.],
        [ 13.,  30.,  86.]])


## **Element wise multiplication**

In [62]:
a = torch.rand(3,3)
print(a)
                
b = torch.FloatTensor([[0, 1, 0],[1,1,1],[0,1,0]])
print(b)                                

c = torch.mul(a,b)                                
print(c)

tensor([[0.5633, 0.5659, 0.9472],
        [0.0787, 0.0882, 0.4865],
        [0.4650, 0.3368, 0.8023]])
tensor([[0., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])
tensor([[0.0000, 0.5659, 0.0000],
        [0.0787, 0.0882, 0.4865],
        [0.0000, 0.3368, 0.0000]])


## **Element wise division**

In [63]:
a = torch.rand(3,3)
print(a)                

b = torch.FloatTensor([[1, 2, 1],[2,2,2],[1,2,1]])
print(b)                                

c = torch.div(a,b)
print(c)

tensor([[0.1933, 0.2242, 0.2812],
        [0.2177, 0.3329, 0.0778],
        [0.1770, 0.6551, 0.9184]])
tensor([[1., 2., 1.],
        [2., 2., 2.],
        [1., 2., 1.]])
tensor([[0.1933, 0.1121, 0.2812],
        [0.1089, 0.1665, 0.0389],
        [0.1770, 0.3276, 0.9184]])


# **Trigonometric Operations in Tensors**

## **Basic Trigonometric operations for tensors**

In [64]:
a = torch.linspace(-1.0, 1.0, steps=10)

print(a)
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.acos(a))
print(torch.atan(a))

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])
tensor([-0.8415, -0.7017, -0.5274, -0.3272, -0.1109,  0.1109,  0.3272,  0.5274,
         0.7017,  0.8415])
tensor([0.5403, 0.7125, 0.8496, 0.9450, 0.9938, 0.9938, 0.9450, 0.8496, 0.7125,
        0.5403])
tensor([-1.5574, -0.9849, -0.6208, -0.3463, -0.1116,  0.1116,  0.3463,  0.6208,
         0.9849,  1.5574])
tensor([-1.5708, -0.8911, -0.5890, -0.3398, -0.1113,  0.1113,  0.3398,  0.5890,
         0.8911,  1.5708])
tensor([3.1416, 2.4619, 2.1598, 1.9106, 1.6821, 1.4595, 1.2310, 0.9818, 0.6797,
        0.0000])
tensor([-0.7854, -0.6610, -0.5071, -0.3218, -0.1107,  0.1107,  0.3218,  0.5071,
         0.6610,  0.7854])


## **Additional Trigonometric operations for tensors**

In [65]:
a = torch.linspace(-1.0, 1.0, steps=10)

print(a)
print(torch.sigmoid(a))
print(torch.tanh(a))
print(torch.log1p(a))
print(torch.erf(a))
print(torch.erfinv(a))

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])
tensor([0.2689, 0.3148, 0.3646, 0.4174, 0.4723, 0.5277, 0.5826, 0.6354, 0.6852,
        0.7311])
tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])
tensor([   -inf, -1.5041, -0.8109, -0.4055, -0.1178,  0.1054,  0.2877,  0.4418,
         0.5754,  0.6931])
tensor([-0.8427, -0.7286, -0.5679, -0.3626, -0.1249,  0.1249,  0.3626,  0.5679,
         0.7286,  0.8427])
tensor([   -inf, -0.8631, -0.5407, -0.3046, -0.0988,  0.0988,  0.3046,  0.5407,
         0.8631,     inf])


# **Comparison operations for tensors**

In [66]:
a = torch.rand(3,3)
print(a)               

b = torch.rand(3,3)
print(b)                                

print(torch.ge(a,b))
print(torch.le(a,b))
print(torch.eq(a,b))
print(torch.ne(a,b))

tensor([[0.7410, 0.7269, 0.3113],
        [0.4025, 0.8574, 0.3757],
        [0.9038, 0.0994, 0.8158]])
tensor([[0.8943, 0.8478, 0.6313],
        [0.0379, 0.6828, 0.5971],
        [0.0340, 0.9279, 0.4626]])
tensor([[False, False, False],
        [ True,  True, False],
        [ True, False,  True]])
tensor([[ True,  True,  True],
        [False, False,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# **Linear Algebraic Operations**

## **Matrix multiplication operations for tensors**

In [67]:
a = torch.ones(2,3)
print("a -")
print(a)
print(a.shape)

print("b -")
b = torch.ones(3,2)
print(b)
print(b.shape)

print("\nMultiplication - ")
print(torch.matmul(a,b))

a -
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
b -
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.Size([3, 2])

Multiplication - 
tensor([[3., 3.],
        [3., 3.]])


## **Batch matrix matrix addition of tensors**

In [68]:
a = torch .ones(2, 2, 3)
print("a-")
print(a)                          
print(a.shape)

b = torch.ones(2, 3, 2)
print("b-")
print(b)
print(b.shape)

print("m-")
m = torch.ones(2,2)
                                                                      
print(m)                                                                              
print(m.shape)
                                                                              

print("BMM- 2 .  3")
print(torch.addbmm(2, m, 3, a, b))

print("BMM- 1 .  1")
print(torch.addbmm(1, m, 1, a, b))


print("BMM-")
print(torch.addbmm(m, a, b))

a-
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
b-
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.Size([2, 3, 2])
m-
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
BMM- 2 .  3
tensor([[20., 20.],
        [20., 20.]])
BMM- 1 .  1
tensor([[7., 7.],
        [7., 7.]])
BMM-
tensor([[7., 7.],
        [7., 7.]])


/tmp/ipykernel_264/3813042772.py:19: UserWarning: This overload of addbmm is deprecated:
	addbmm(Number beta, Tensor input, Number alpha, Tensor batch1, Tensor batch2, *, Tensor out)
Consider using one of the following signatures instead:
	addbmm(Tensor input, Tensor batch1, Tensor batch2, *, Number beta, Number alpha, Tensor out) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:1050.)
  print(torch.addbmm(2, m, 3, a, b))


## **Non Batch matrix matrix addition of tensors**

In [69]:
a = torch.ones(2, 3)
print("a-") 
print(a)
print(a.shape)

b = torch.ones(3, 2)
print("b-")        
print(b)
print(b.shape)

m = torch.ones(2,2)
print("m-") 
                        
print(m)
print(m.shape)

print("ADDMM")
print(torch.addmm(m, a, b))

print("ADDMM - 2 . 3")
print(torch.addmm(2, m, 3, a, b))

print("ADDMM - 1 . 1")
print(torch.addmm(1, m, 1, a, b))

a-
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
b-
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.Size([3, 2])
m-
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
ADDMM
tensor([[4., 4.],
        [4., 4.]])
ADDMM - 2 . 3
tensor([[11., 11.],
        [11., 11.]])
ADDMM - 1 . 1
tensor([[4., 4.],
        [4., 4.]])


## **matrix vector addition of tensors**

In [70]:
a = torch.ones(2, 3)
print("a - ")        
print(a)
print(a.shape)


b = torch.ones(3)
print("b - ")        
print(b)
print(b.shape)

m = torch.ones(2)
print("m - ")        
print(m)
print(m.shape)
        
print("ADDMV- 2 . 2")        
torch.addmv(2,m,3,a,b)

print("ADDMV- 1 . 1")                
torch.addmv(1,m,1,a,b)

print("ADDMV-")   
torch.addmv(m,a,b)

a - 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
b - 
tensor([1., 1., 1.])
torch.Size([3])
m - 
tensor([1., 1.])
torch.Size([2])
ADDMV- 2 . 2
ADDMV- 1 . 1
ADDMV-


tensor([4., 4.])

## **Outer product of vectors**

In [71]:
a = torch.tensor([1.0, 2.0, 3.0])
print("a - ")        
print(a)
print(a.shape)


b = a

m = torch.ones(3,3)
print("m - ")        
print(m)
print(m.shape)

print("ADDR -")                    
print(torch.addr(m,a,b))
        
m = torch.zeros(3,3)

print("m - ")        
print(m)
                
print("ADDR -")    
print(torch.addr(m,a,b))

a - 
tensor([1., 2., 3.])
torch.Size([3])
m - 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])
ADDR -
tensor([[ 2.,  3.,  4.],
        [ 3.,  5.,  7.],
        [ 4.,  7., 10.]])
m - 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ADDR -
tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])


## **Illustration for baddbmm**

In [72]:
a = torch.ones(2,2,3)
print("a - ")        
print(a)
print(a.shape)
                          
b = torch.ones(2,3,2)
print("b - ")        
print(b)
print(b.shape)                                                                      


m = torch.ones(2, 2, 2)
print("m - ")        
print(m)
print(m.shape)                                                                                                

print("BADDBMM - 1,m,1,a,b")
print(torch.baddbmm(1,m,1,a,b))

print("BADDBMM - 2,m,1,a,b")
print(torch.baddbmm(2,m,1,a,b))

print("BADDBMM - 1,m,3,a,b")
print(torch.baddbmm(1,m,2,a,b))

a - 
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
b - 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.Size([2, 3, 2])
m - 
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([2, 2, 2])
BADDBMM - 1,m,1,a,b
tensor([[[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]]])
BADDBMM - 2,m,1,a,b
tensor([[[5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.]]])
BADDBMM - 1,m,3,a,b
tensor([[[7., 7.],
         [7., 7.]],

        [[7., 7.],
         [7., 7.]]])


## **Illustration for batch-wise matrix multiplication**

In [73]:
a = torch.ones(2,2,3)
print("a - ")        
print(a)
print(a.shape)                                                                                                

b = torch.ones(2,3,2)
print("b - ")        
print(b)
print(b.shape)                                                                                                

print("BMM a.b")
print(torch.bmm(a,b))

a - 
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
b - 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.Size([2, 3, 2])
BMM a.b
tensor([[[3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.]]])


## **Dot product for tensors**

In [74]:
a = torch.rand(3)
print("a-")
print(a)

b = torch.rand(3)
print("b-")
print(b)

print("Dot -- A.b")
print(torch.dot(a,b))

a-
tensor([0.1147, 0.2184, 0.0627])
b-
tensor([0.8914, 0.1353, 0.6794])
Dot -- A.b
tensor(0.1744)


## **Compute Eigen values**

In [75]:
a = torch.rand(3,3)
print("a-",a)                

values, vectors = torch.eig(a, eigenvectors=True)
print("Values:",values)
print("Vectors:",vectors)

print(values[0,0] * vectors[:,0].reshape(3,1))
print(torch.mm(a, vectors[:,0].reshape(3,1)))

a- tensor([[0.9575, 0.1461, 0.6842],
        [0.5801, 0.0996, 0.1264],
        [0.2193, 0.4995, 0.1721]])
Values: tensor([[ 1.3189,  0.0000],
        [-0.0448,  0.3092],
        [-0.0448, -0.3092]])
Vectors: tensor([[-0.8323,  0.4027,  0.2010],
        [-0.4320,  0.1310, -0.5270],
        [-0.3473, -0.7089,  0.0000]])
tensor([[-1.0977],
        [-0.5697],
        [-0.4581]])
tensor([[-1.0977],
        [-0.5697],
        [-0.4581]])


/tmp/ipykernel_264/93519019.py:4: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2894.)
  values, vectors = torch.eig(a, eigenvectors=True)


## **Cross product of two tensors**

In [76]:
a = torch.rand(3)
b = torch.rand(3)

print("Cross Product ")
print(torch.cross(a,b))

Cross Product 
tensor([ 0.0371,  0.2195, -0.3233])


## **Compute the norm of a tensor**

In [77]:
a = torch.ones(4)

print("Norm(a,1)-")
print(torch.norm(a,1))

print("Norm(a,2)-")
print(torch.norm(a,2))

print("Norm(a,3)-")
print(torch.norm(a,3))

print("Norm(a,4)-")
print(torch.norm(a,4))

print("Norm(a,5)-")
print(torch.norm(a,5))

print("Norm(a,Inf)-")
print(torch.norm(a,float('inf')))

Norm(a,1)-
tensor(4.)
Norm(a,2)-
tensor(2.)
Norm(a,3)-
tensor(1.5874)
Norm(a,4)-
tensor(1.4142)
Norm(a,5)-
tensor(1.3195)
Norm(a,Inf)-
tensor(1.)


## **Normalize a tensor**

In [78]:
a = torch.FloatTensor([[1,2,3,4]])
print("a-")
print(a)

print("renorm(a)")
print(torch.renorm(a, dim=0, p=2, maxnorm=1))

a-
tensor([[1., 2., 3., 4.]])
renorm(a)
tensor([[0.1826, 0.3651, 0.5477, 0.7303]])
